### PR TITLE
[Feature] Blade Components

### PR DESCRIPTION
**Pull request by ryangjchandler**
This pull request adds support for Laravel Blade Components using the new `<x-component>` syntax.

There isn't currently any support for auto-magically registering / discovering components, so instead it has to be done through a filter.

```php
add_filter('bladepress/components', function ($components) {
    $components['example'] = TestComponent::class;

    return $components;
})
```

Then, inside of your Blade template you can do `<x-example />`.

You can also pass through attributes etc - the component class will receive them inside of a constructor.

It's also worth noting that the Blade compiler is a bit funny about classes in the global namespace, so you'll need to make sure you namespace your component class.

If you want to use anonymous components, you can either pass in the name of a view instead of a class, or ensure there is a `components` directory in the root of your `views` folder.

### CODE REVIEW

**Comment by ryangjchandler** [comment]
@PaulMorel - fancy reviewing?

**Comment by ryangjchandler** [comment]
@PaulMorel, @jreviews - I've also made a change so that calling `view()` doesn't echo the contents by default, what do you think? It makes the Blade components nicer since you don't have to ensure you're passing `$echo = true`, as well as things like controllers, etc.

**Comment by jreviews** [comment]
@ryangjchandler Any reason why this is described as being for WordPress themes, and not plugins as well? I see you have the `current_theme_supports('bladepress')` check in place. 

I agree that not echoing by default is useful.

**Comment by ryangjchandler** [comment]
> @ryangjchandler Any reason why this is described as being for WordPress themes, and not plugins as well? I see you have the `current_theme_supports('bladepress')` check in place.
> 
> I agree that not echoing by default is useful.

Good point - in reality, I don't think plugins should rely on other plugins being installed. The plugin could of course add theme support too.

**Pull request merged**
