### PR TITLE
[Feature] Directives

### PR DESCRIPTION
**Pull request by ryangjchandler**
This PR adds support for some of the Laravel specific directives by overwriting them and using WordPress equivalents. There is also some helper directives for things like `WP_DEBUG` and similar.

### CODE REVIEW

**Comment by ryangjchandler** [comment]
@jreviews - another one here with some of the common directives adapted for WordPress, as well as nice helper one for actions, filters and common content related functions.

**Comment by PaulMorel** [comment]
`@endauth` and `@endguest` should probably be added too!

**Comment by ryangjchandler** [comment]
> `@endauth` and `@endguest` should probably be added too!

No need for those really since all it does is close an if statement, no WP specific stuff needed.

**Comment by ryangjchandler** [comment]
> > `@endauth` and `@endguest` should probably be added too!
> 
> No need for those really since all it does is close an if statement, no WP specific stuff needed. 

Would also mean I can get rid of any of the others I've overwritten that just closes an if statement.

**Comment by PaulMorel** [comment]
That's true, but I think it could be good to try to keep parity with Laravel. It could would help reduce the friction between switching from Blade on Laravel to Blade on WordPress.

Also, `@auth @endauth` reads slightly better than `@auth @endif` even if both are compiled equally.

**Comment by ryangjchandler** [comment]
That's what I'm saying - endauth & endguest are already implemented by Laravel, so there's nothing for me to do since they just close the if statement - there's no need for me to overwrite them.

**Comment by PaulMorel** [comment]
Huh, you're right. In my initial tests `@endauth` simply got printed to the page instead of being compiled. I must've been doing something wrong. Sorry for the confusion!

**Pull request merged**
